name: Architecture Benchmark
on: [push, pull_request]
env:
  RUSTFLAGS: -C target-cpu=native
  NALGEBRA_LAPACK_BACKEND: openblas

permissions:
  contents: write # This gives the workflow permission to push changes

jobs:
  benchmark:
    strategy:
      matrix:
        include:
          - arch: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            blas: libopenblas-dev

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Ensure we have full git history and can push back
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.blas }} liblapack-dev

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}

      - name: Run Benchmarks
        run: |
          # Ensure assets directory exists
          mkdir -p assets

          # Run benchmarks for the specific target
          cargo bench --all-features --target ${{ matrix.arch }}

          # Find and copy the violin plot, with architecture-specific naming
          find target/criterion -name "violin.svg" -exec cp {} "assets/${{ matrix.arch }}_violins.svg" \;

      - name: Commit and Push SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Check if there are any changes in the assets directory
          if [[ -n $(git status assets/ -s) ]]; then
            git add assets/
            git commit -m "Update benchmark SVG for ${{ matrix.arch }}"
            git push
          fi
