name: Architecture Benchmark
on: [push, pull_request]
env:
  RUSTFLAGS: -C target-cpu=native
  NALGEBRA_LAPACK_BACKEND: openblas

jobs:
  benchmark:
    strategy:
      matrix:
        include:
          - arch: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            blas: libopenblas-dev

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.blas }} liblapack-dev

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}

      - name: Run Benchmarks
        run: |
          # Ensure assets directory exists
          mkdir -p assets

          # Run benchmarks for the specific target
          cargo bench --all-features --target ${{ matrix.arch }}

          # Debug: List contents of criterion directory
          find target/criterion -type f

          # Find and copy the violin plot, with architecture-specific naming
          find target/criterion -name "violin.svg" -exec cp {} "assets/${{ matrix.arch }}_violins.svg" \;

          # Debug: List contents of assets directory
          ls -l assets

      - name: Upload Benchmark Assets
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-plots-${{ matrix.arch }}
          path: assets/

      - name: Commit SVG Files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Check if there are any changes
          if [[ -n $(git status -s) ]]; then
            git add assets/
            git commit -m "Update benchmark SVG for ${{ matrix.arch }}"
            git push
          fi
