name: Architecture Benchmark
on: [push, pull_request]
env:
  RUSTFLAGS: -C target-cpu=native
  NALGEBRA_LAPACK_BACKEND: openblas

jobs:
  benchmark:
    strategy:
      matrix:
        arch:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
        include:
          - arch: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            blas: libopenblas-dev
          - arch: aarch64-unknown-linux-gnu
            runner: ubuntu-latest-arm64
            blas: libopenblas-dev
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.blas }} liblapack-dev

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}

      - name: Run Benchmarks
        run: |
          cargo bench --all-features --target ${{ matrix.arch }}

          # Create assets directory if it doesn't exist
          mkdir -p assets

          # Find and copy the violin plot, with architecture-specific naming
          find target/criterion -name "violin.svg" -exec cp {} "assets/${{ matrix.arch }}_violins.svg" \;

      - name: Upload Violin Plot
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-plots-${{ matrix.arch }}
          path: assets/${{ matrix.arch }}_violins.svg
