name: Cross-Architecture Benchmarks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Dockerfile for Benchmarking
        run: |
          cat > Dockerfile.benchmark <<EOF
          FROM rust:latest

          # Install dependencies
          RUN apt-get update && apt-get install -y \
              libopenblas-dev \
              liblapack-dev

          # Set working directory
          WORKDIR /benchmark

          # Copy project files
          COPY . .

          # Install Rust targets
          RUN rustup target add x86_64-unknown-linux-gnu
          RUN rustup target add aarch64-unknown-linux-gnu

          # Run benchmarks and generate plots
          CMD ["sh", "-c", "cargo bench --all-features --target x86_64-unknown-linux-gnu && cargo bench --all-features --target aarch64-unknown-linux-gnu"]
          EOF

      - name: Run Benchmarks
        run: |
          # Create assets directory
          mkdir -p assets

          # Build and run benchmarks for each architecture
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f Dockerfile.benchmark \
            -t benchmark-runner \
            --output type=local,dest=./benchmark-output \
            .

      - name: Process Benchmark Results
        run: |
          # Copy violin plots from benchmark outputs
          find benchmark-output -name "violin.svg" -exec cp {} assets/ \;

          # Rename plots to be architecture-specific
          mv assets/violin.svg assets/x86_64_violins.svg
          mv assets/violin.svg assets/aarch64_violins.svg

      - name: Update README
        run: |
          # Basic script to update README with new benchmark plots
          sed -i 's|!\[x86_64 Benchmark\](.*)|![x86_64 Benchmark](assets/x86_64_violins.svg)|' README.md
          sed -i 's|!\[aarch64 Benchmark\](.*)|![aarch64 Benchmark](assets/aarch64_violins.svg)|' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add assets/x86_64_violins.svg assets/aarch64_violins.svg README.md
          git commit -m "Update benchmark plots" || echo "No changes to commit"
          git push
