name: Architecture Benchmark
on: [push, pull_request]
env:
  RUSTFLAGS: -C target-cpu=native
  NALGEBRA_LAPACK_BACKEND: openblas

jobs:
  benchmark:
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu22.04
            target: aarch64-unknown-linux-gnu
          - arch: x86_64
            distro: ubuntu22.04
            target: x86_64-unknown-linux-gnu

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Benchmarks on ${{ matrix.arch }}
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}

          # Setup steps
          setup: |
            mkdir -p "${PWD}/assets"

          # Install dependencies
          install: |
            apt-get update
            apt-get install -y curl build-essential libopenblas-dev liblapack-dev

          # Install Rust
          run: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source "$HOME/.cargo/env"
            rustup default stable
            rustup target add ${{ matrix.target }}

            # Clone the repository
            git clone ${{ github.server_url }}/${{ github.repository }} repo
            cd repo

            # Run benchmarks
            cargo bench --all-features --target ${{ matrix.target }}

            # Find and copy violin plot
            find target/criterion -name "violin.svg" -exec cp {} "/assets/${{ matrix.target }}_violins.svg" \;

      - name: Upload Violin Plot
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-plots-${{ matrix.target }}
          path: assets/${{ matrix.target }}_violins.svg
