name: Architecture Benchmark
on: [push, pull_request]
env:
  RUSTFLAGS: -C target-cpu=native
  NALGEBRA_LAPACK_BACKEND: openblas

permissions:
  contents: write

jobs:
  benchmark:
    strategy:
      matrix:
        include:
          - arch: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            blas: libopenblas-dev

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.blas }} liblapack-dev

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}

      - name: Run Benchmarks
        run: |
          mkdir -p assets
          cargo bench --all-features --target ${{ matrix.arch }}

          # Copy both f32 and f64 plots with architecture prefix
          find target/criterion/f64/report target/criterion/f32/report -name "violin.svg" -exec sh -c '
            for svg_file do
              dir_name=$(dirname "$svg_file")
              type_name=${dir_name##*/}
              cp "$svg_file" "assets/${{ matrix.arch }}_${type_name}.svg"
            done
          ' sh {} +

      - name: Commit and Push SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          if [[ -n $(git status assets/ -s) ]]; then
            git add assets/
            git commit -m "Update benchmark SVGs for ${{ matrix.arch }} (f32/f64)"
            git push
          fi
